# Generated by Django 5.2.6 on 2025-09-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_cancelado_pedido_fecha_cancelacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'MESERO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
