# Generated by Django 5.2.6 on 2025-09-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='creado_por',
            new_name='empleado',
        ),
    ]
