# Generated by Django 5.2.6 on 2025-09-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_rename_creado_por_pedido_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'CLIENTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_como_cliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
