# Generated by Django 5.2.6 on 2025-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='True = stock ya bloqueado para este pedido'),
        ),
    ]
