# Generated by Django 5.2.6 on 2025-09-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_pedido_bloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bloqueado',
        ),
    ]
