# Generated by Django 5.2.6 on 2025-09-26 21:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_fin', models.TimeField(default=datetime.time(21, 4, 6, 803526), editable=False)),
                ('hora_inicio', models.TimeField(default=datetime.time(21, 4, 6, 803588))),
                ('numero_personas', models.PositiveIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.estadoreserva')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mesa', 'fecha', 'hora_inicio')},
            },
        ),
    ]
