# Generated by Django 5.2.6 on 2025-09-30 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_hora_fin_alter_reserva_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(15, 41, 20, 355287), editable=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
