# Generated by Django 5.2.6 on 2025-09-30 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_hora_fin_alter_reserva_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 27, 41, 288240), editable=False),
        ),
    ]
