# Generated by Django 5.2.6 on 2025-09-30 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 37, 1, 722982), editable=False),
        ),
    ]
