# Generated by Django 5.2.6 on 2025-10-06 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(1, 53, 34, 904191), editable=False),
        ),
    ]
