# Generated by Django 5.2.6 on 2025-10-08 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(15, 21, 49, 189870), editable=False),
        ),
    ]
