# Generated by Django 5.2.6 on 2025-11-05 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(23, 50, 24, 254323), editable=False),
        ),
    ]
