# Generated by Django 5.2.6 on 2025-11-06 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(1, 23, 33, 530479), editable=False),
        ),
    ]
