# Generated by Django 5.2.6 on 2025-11-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_reserva_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_confirmacion',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(editable=False),
        ),
    ]
