# Generated by Django 5.2.6 on 2025-10-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('usuario_registrado', 'Usuario registrado'), ('pedido_creado', 'Pedido creado'), ('pedido_entregado', 'Pedido entregado'), ('pedido_cancelado', 'Pedido cancelado'), ('reserva_creada', 'Reserva creada'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_cancelada', 'Reserva cancelada'), ('credito_aprobado', 'Crédito aprobado'), ('consumo_credito_realizado', 'Consumo de crédito realizado'), ('pago_credito_confirmado', 'Pago de crédito confirmado'), ('credito_suspendido', 'Crédito suspendido'), ('credito_pagado_total', 'Crédito pagado total'), ('stock_bajo_alcanzado', 'Stock bajo alcanzado'), ('producto_agotado', 'Producto agotado')], max_length=50)),
                ('destinatario', models.CharField(max_length=255)),
                ('contexto_json', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('reintentando', 'Reintentando')], default='pendiente', max_length=20)),
                ('intento', models.PositiveSmallIntegerField(default=0)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3)),
                ('prox_reintento', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionLeida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('notificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('usuario_registrado', 'Usuario registrado'), ('pedido_creado', 'Pedido creado'), ('pedido_entregado', 'Pedido entregado'), ('pedido_cancelado', 'Pedido cancelado'), ('reserva_creada', 'Reserva creada'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_cancelada', 'Reserva cancelada'), ('credito_aprobado', 'Crédito aprobado'), ('consumo_credito_realizado', 'Consumo de crédito realizado'), ('pago_credito_confirmado', 'Pago de crédito confirmado'), ('credito_suspendido', 'Crédito suspendido'), ('credito_pagado_total', 'Crédito pagado total'), ('stock_bajo_alcanzado', 'Stock bajo alcanzado'), ('producto_agotado', 'Producto agotado')], max_length=50)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('cuerpo_txt', models.TextField()),
                ('cuerpo_html', models.TextField(blank=True, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.canal')),
            ],
            options={
                'unique_together': {('evento', 'canal', 'idioma')},
            },
        ),
        migrations.AddField(
            model_name='notificacion',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.plantilla'),
        ),
        migrations.CreateModel(
            name='PreferenciaCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('usuario_registrado', 'Usuario registrado'), ('pedido_creado', 'Pedido creado'), ('pedido_entregado', 'Pedido entregado'), ('pedido_cancelado', 'Pedido cancelado'), ('reserva_creada', 'Reserva creada'), ('reserva_confirmada', 'Reserva confirmada'), ('reserva_cancelada', 'Reserva cancelada'), ('credito_aprobado', 'Crédito aprobado'), ('consumo_credito_realizado', 'Consumo de crédito realizado'), ('pago_credito_confirmado', 'Pago de crédito confirmado'), ('credito_suspendido', 'Crédito suspendido'), ('credito_pagado_total', 'Crédito pagado total'), ('stock_bajo_alcanzado', 'Stock bajo alcanzado'), ('producto_agotado', 'Producto agotado')], max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.canal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
