# Generated by Django 5.2.6 on 2025-09-30 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientocredito',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='saldo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('limite__gt', 0)), name='limite_positivo'),
        ),
    ]
