# Generated by Django 5.2.6 on 2025-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_alter_movimientocredito_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
