# Generated by Django 5.2.6 on 2025-09-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_alter_credito_saldo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credito',
            name='saldo_no_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='credito',
            name='limite_positivo',
        ),
    ]
