# Generated by Django 5.2.6 on 2025-10-01 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_remove_credito_saldo_no_negativo_and_more'),
        ('pedidos', '0009_remove_detallepedido_observacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocredito',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_credito', to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to=settings.AUTH_USER_MODEL),
        ),
    ]
