# Generated by Django 5.2.6 on 2025-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_estadosolicitud_solicitudacreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudacreditacion',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, help_text='Fecha en que fue rechazada (bloqueo 15 días)', null=True),
        ),
    ]
