# Generated by Django 5.2.6 on 2025-09-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='stock_bloqueado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
