# Generated by Django 5.2.6 on 2025-10-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productovariante_stock_bloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='activo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='stock_bloqueado',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
