# Generated by Django 5.2.6 on 2025-11-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_productovariante_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='imagen_variante',
            field=models.ImageField(blank=True, null=True, upload_to='variantes'),
        ),
    ]
