# Generated by Django 5.2.6 on 2025-10-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('MESERO', 'Mesero'), ('COCINERO', 'Cocinero')], default='CLIENTE', max_length=20),
        ),
    ]
